# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/training/git/avnet/hdl/Projects/ultra96v2_oob/ULTRA96V2_2019_1/ultra96v2_oob.srcs/sources_1/bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_5/ultra96v2_oob_auto_ds_5.xci
# IP: The module: 'ultra96v2_oob_auto_ds_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/training/git/avnet/hdl/Projects/ultra96v2_oob/ULTRA96V2_2019_1/ultra96v2_oob.srcs/sources_1/bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_5/ultra96v2_oob_auto_ds_5_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_oob_auto_ds_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/training/git/avnet/hdl/Projects/ultra96v2_oob/ULTRA96V2_2019_1/ultra96v2_oob.srcs/sources_1/bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_5/ultra96v2_oob_auto_ds_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_oob_auto_ds_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/training/git/avnet/hdl/Projects/ultra96v2_oob/ULTRA96V2_2019_1/ultra96v2_oob.srcs/sources_1/bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_5/ultra96v2_oob_auto_ds_5.xci
# IP: The module: 'ultra96v2_oob_auto_ds_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/training/git/avnet/hdl/Projects/ultra96v2_oob/ULTRA96V2_2019_1/ultra96v2_oob.srcs/sources_1/bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_5/ultra96v2_oob_auto_ds_5_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_oob_auto_ds_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/training/git/avnet/hdl/Projects/ultra96v2_oob/ULTRA96V2_2019_1/ultra96v2_oob.srcs/sources_1/bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_5/ultra96v2_oob_auto_ds_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultra96v2_oob_auto_ds_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
