# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableLutRouteBelPower 1
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 2
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
create_project -in_memory -part xczu3eg-sbva484-1-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/parallels/ultra96v2_0/ultra96v2_0.cache/wt [current_project]
set_property parent.project_path /home/parallels/ultra96v2_0/ultra96v2_0.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:ultra96v2:part0:1.0 [current_project]
set_property ip_output_repo /home/parallels/ultra96v2_0/ultra96v2_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/new/axis_sm.v
  /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/new/ultra96v2_wrapper.v
}
add_files /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ultra96v2_0.bd
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_zynq_ultra_ps_e_0_0/ultra96v2_0_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_zynq_ultra_ps_e_0_0/ultra96v2_0_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_axi_gpio_0_0/ultra96v2_0_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_axi_gpio_0_0/ultra96v2_0_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_axi_gpio_0_0/ultra96v2_0_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_xbar_0/ultra96v2_0_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_rst_ps8_0_100M_0/ultra96v2_0_rst_ps8_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_rst_ps8_0_100M_0/ultra96v2_0_rst_ps8_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_rst_ps8_0_100M_0/ultra96v2_0_rst_ps8_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_axi_gpio_1_0/ultra96v2_0_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_axi_gpio_1_0/ultra96v2_0_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_axi_gpio_1_0/ultra96v2_0_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_axi_uart16550_0_0/ultra96v2_0_axi_uart16550_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_axi_uart16550_0_0/ultra96v2_0_axi_uart16550_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_axi_uart16550_0_0/ultra96v2_0_axi_uart16550_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_blk_mem_gen_0_0/ultra96v2_0_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_axi_bram_ctrl_0_0/ultra96v2_0_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_ds_0/ultra96v2_0_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_ds_0/ultra96v2_0_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_ds_0/ultra96v2_0_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_pc_0/ultra96v2_0_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_ds_1/ultra96v2_0_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_ds_1/ultra96v2_0_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_ds_1/ultra96v2_0_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_pc_1/ultra96v2_0_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_ds_2/ultra96v2_0_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_ds_2/ultra96v2_0_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_ds_2/ultra96v2_0_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_pc_2/ultra96v2_0_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_ds_3/ultra96v2_0_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_ds_3/ultra96v2_0_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ip/ultra96v2_0_auto_ds_3/ultra96v2_0_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/bd/ultra96v2_0/ultra96v2_0_ooc.xdc]

read_ip -quiet /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0_ooc.xdc]

read_ip -quiet /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/parallels/ultra96v2_0/ultra96v2_0.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/parallels/ultra96v2_0/ultra96v2_0.srcs/constrs_1/new/ultra96v2_0.xdc
set_property used_in_implementation false [get_files /home/parallels/ultra96v2_0/ultra96v2_0.srcs/constrs_1/new/ultra96v2_0.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ultra96v2_wrapper -part xczu3eg-sbva484-1-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ultra96v2_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ultra96v2_wrapper_utilization_synth.rpt -pb ultra96v2_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
