# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ultra96v2_oob/ultra96v2_oob.xdc

# Block Designs: bd/ultra96v2_oob/ultra96v2_oob.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob || ORIG_REF_NAME==ultra96v2_oob} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_zynq_ultra_ps_e_0_0/ultra96v2_oob_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ultra96v2_oob_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xbar_0/ultra96v2_oob_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xbar_0 || ORIG_REF_NAME==ultra96v2_oob_xbar_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_axi_interconnect_0_0/ultra96v2_oob_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_axi_interconnect_0_0 || ORIG_REF_NAME==ultra96v2_oob_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_proc_sys_reset_0_0/ultra96v2_oob_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_proc_sys_reset_0_0 || ORIG_REF_NAME==ultra96v2_oob_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_axi_bram_ctrl_0_0/ultra96v2_oob_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ultra96v2_oob_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_blk_mem_gen_0_0/ultra96v2_oob_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_blk_mem_gen_0_0 || ORIG_REF_NAME==ultra96v2_oob_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_axi_uart16550_0_0/ultra96v2_oob_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_axi_uart16550_0_0 || ORIG_REF_NAME==ultra96v2_oob_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_axi_uart16550_1_0/ultra96v2_oob_axi_uart16550_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_axi_uart16550_1_0 || ORIG_REF_NAME==ultra96v2_oob_axi_uart16550_1_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_axi_gpio_0_0/ultra96v2_oob_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_axi_gpio_0_0 || ORIG_REF_NAME==ultra96v2_oob_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_axi_gpio_1_0/ultra96v2_oob_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_axi_gpio_1_0 || ORIG_REF_NAME==ultra96v2_oob_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_axi_gpio_2_0/ultra96v2_oob_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_axi_gpio_2_0 || ORIG_REF_NAME==ultra96v2_oob_axi_gpio_2_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_PWM_w_Int_0_0/ultra96v2_oob_PWM_w_Int_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_PWM_w_Int_0_0 || ORIG_REF_NAME==ultra96v2_oob_PWM_w_Int_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_PWM_w_Int_1_0/ultra96v2_oob_PWM_w_Int_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_PWM_w_Int_1_0 || ORIG_REF_NAME==ultra96v2_oob_PWM_w_Int_1_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_system_management_wiz_0_0/ultra96v2_oob_system_management_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_system_management_wiz_0_0 || ORIG_REF_NAME==ultra96v2_oob_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlconcat_0_0/ultra96v2_oob_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlconcat_0_0 || ORIG_REF_NAME==ultra96v2_oob_xlconcat_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_0_0/ultra96v2_oob_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_0_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_0_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_1_0/ultra96v2_oob_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_1_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_1_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_2_0/ultra96v2_oob_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_2_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_2_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_3_0/ultra96v2_oob_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_3_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_3_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_4_0/ultra96v2_oob_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_4_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_4_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_5_0/ultra96v2_oob_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_5_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_5_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_6_0/ultra96v2_oob_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_6_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_6_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_7_0/ultra96v2_oob_xlslice_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_7_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_7_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_8_0/ultra96v2_oob_xlslice_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_8_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_8_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_xlslice_9_0/ultra96v2_oob_xlslice_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_xlslice_9_0 || ORIG_REF_NAME==ultra96v2_oob_xlslice_9_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_0/ultra96v2_oob_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_ds_0 || ORIG_REF_NAME==ultra96v2_oob_auto_ds_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_pc_0/ultra96v2_oob_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_pc_0 || ORIG_REF_NAME==ultra96v2_oob_auto_pc_0} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_1/ultra96v2_oob_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_ds_1 || ORIG_REF_NAME==ultra96v2_oob_auto_ds_1} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_pc_1/ultra96v2_oob_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_pc_1 || ORIG_REF_NAME==ultra96v2_oob_auto_pc_1} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_2/ultra96v2_oob_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_ds_2 || ORIG_REF_NAME==ultra96v2_oob_auto_ds_2} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_pc_2/ultra96v2_oob_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_pc_2 || ORIG_REF_NAME==ultra96v2_oob_auto_pc_2} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_3/ultra96v2_oob_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_ds_3 || ORIG_REF_NAME==ultra96v2_oob_auto_ds_3} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_pc_3/ultra96v2_oob_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_pc_3 || ORIG_REF_NAME==ultra96v2_oob_auto_pc_3} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_4/ultra96v2_oob_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_ds_4 || ORIG_REF_NAME==ultra96v2_oob_auto_ds_4} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_pc_4/ultra96v2_oob_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_pc_4 || ORIG_REF_NAME==ultra96v2_oob_auto_pc_4} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_5/ultra96v2_oob_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_ds_5 || ORIG_REF_NAME==ultra96v2_oob_auto_ds_5} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_pc_5/ultra96v2_oob_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_pc_5 || ORIG_REF_NAME==ultra96v2_oob_auto_pc_5} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_6/ultra96v2_oob_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_ds_6 || ORIG_REF_NAME==ultra96v2_oob_auto_ds_6} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_pc_6/ultra96v2_oob_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_pc_6 || ORIG_REF_NAME==ultra96v2_oob_auto_pc_6} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_ds_7/ultra96v2_oob_auto_ds_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_ds_7 || ORIG_REF_NAME==ultra96v2_oob_auto_ds_7} -quiet] -quiet

# IP: bd/ultra96v2_oob/ip/ultra96v2_oob_auto_pc_7/ultra96v2_oob_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ultra96v2_oob_auto_pc_7 || ORIG_REF_NAME==ultra96v2_oob_auto_pc_7} -quiet] -quiet

# XDC: bd/ultra96v2_oob/ultra96v2_oob_ooc.xdc
